import React, { useState } from 'react';
import { FileDown, BookOpen, ChevronDown, ChevronUp, CheckCircle, Terminal, Smartphone, Zap, ShieldCheck } from 'lucide-react';

const walkthroughContent = `
MOBILE AGENT SIMULATION — WALKTHROUGH
======================================
Financial AI SOC | UPI Fraud Detection System
Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The Mobile Agent Simulation layer demonstrates how an on-device SOC agent 
protects users from UPI fraud, phishing, and compromised environments.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NEW FEATURES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. IMMERSIVE MOBILE AGENT (MobileAgent.jsx)
   A dedicated component that simulates a high-end mobile phone:
   • Interactive Camera: Includes a scanning animation and shutter effect.
   • Agentic Monitoring Bar: Real-time status for EDR, OS Integrity (Root),
     and Screen Recording.
   • Notification Center: Slide-down alerts for both bank transactions and
     SOC threat detections.

2. MERCHANT QR GENERATION
   Updated the legacy simulator to act as a merchant terminal:
   • Valid QR: Generates a standard merchant payment link.
   • Malicious QR: Generates a phishing link that triggers the SOC agent's
     URL analysis engine.

3. AGENTIC WORKFLOW
   • Pre-scan Check: Monitors device health before scanning.
   • Deep Link Analysis: Intercepts the scanned URL and queries the backend
     for phishing detection.
   • Post-Transaction Verification: "Intercepts" the bank's SMS/Notification
     to verify the final amount against the original intent.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HOW TO TEST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Step 1 → Go to the "Mobile Agent" tab in the sidebar.
Step 2 → Go to the "Legacy Simulator" tab and click "Malicious QR"
          in the Generator section.
Step 3 → Copy the malicious URL displayed.
Step 4 → Go back to "Mobile Agent" and paste the URL in the
          "Mock QR URL" input field.
Step 5 → Click "Scan Any QR" and observe the camera detecting
          and analyzing the threat.
Step 6 → Observe the SOC Alert slide down from the top of the
          mobile screen.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TECHNICAL IMPLEMENTATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Frontend:  React + Lucide Icons + CSS Animations
Backend:   Integrated with /qr/analyze and /transaction/detect endpoints
           in socRoutes.js
State Mgmt: Real-time feedback loop between device health and risk scoring

Core Modules:
  🔐 QR Validator      — Decodes & validates UPI IDs from static/dynamic QR codes
  📱 Notification Parser — Listens for GPay, PhonePe, BHIM alerts
  📨 SMS Analyzer      — Parses bank SMS alerts, detects OTP phishing
  ⚡ Risk Engine       — Real-time ML scoring of fraud probability
  📍 Geo-Tracker       — Detects impossible travel, VPN usage patterns
  🚨 Alert Manager     — Encrypted push notifications to SOC dashboard

Android Permissions Required:
  • Notification Access — Required for payment app monitoring
  • SMS Read            — Bank alert & OTP analysis
  • Device State & Location — Risk scoring & anomaly detection

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DEPLOYMENT & COVERAGE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Platform:     Android 8+
Agent Status: ● Live (Passive monitoring active)
Coverage:     2,340 Devices | 12 Regions | 99.4% Uptime
Transactions: 15.2M daily transactions monitored

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Financial AI SOC | Confidential
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

const steps = [
  {
    icon: <Smartphone size={18} />,
    label: 'Step 1',
    title: 'Open Mobile Agent Tab',
    desc: 'Navigate to the Mobile Agent section from the left sidebar.',
    color: 'var(--color-verified)',
  },
  {
    icon: <Terminal size={18} />,
    label: 'Step 2',
    title: 'Generate Malicious QR',
    desc: 'Go to Legacy Simulator → Generator section → click "Malicious QR".',
    color: 'var(--color-fraud)',
  },
  {
    icon: <CheckCircle size={18} />,
    label: 'Step 3',
    title: 'Copy the Phishing URL',
    desc: 'Copy the malicious URL generated by the simulator.',
    color: 'var(--color-warning)',
  },
  {
    icon: <Zap size={18} />,
    label: 'Step 4',
    title: 'Paste & Scan',
    desc: 'Paste the URL into the "Mock QR URL" input on the Mobile Agent page and click "Scan Any QR".',
    color: 'var(--color-verified)',
  },
  {
    icon: <ShieldCheck size={18} />,
    label: 'Step 5 & 6',
    title: 'Observe SOC Alert',
    desc: 'Watch the camera detect the threat and observe the SOC Alert sliding down from the top.',
    color: '#a78bfa',
  },
];

const WalkthroughPanel = () => {
  const [open, setOpen] = useState(false);

  const handleDownload = () => {
    const blob = new Blob([walkthroughContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Mobile_Agent_Simulation_Walkthrough.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className="glass-panel"
      style={{
        gridColumn: 'span 12',
        border: '1px solid rgba(167, 139, 250, 0.25)',
        background: 'linear-gradient(135deg, rgba(167,139,250,0.05) 0%, rgba(99,102,241,0.05) 100%)',
      }}
    >
      {/* Header Row */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: '1rem',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <div
            style={{
              width: '40px',
              height: '40px',
              borderRadius: '10px',
              background: 'linear-gradient(135deg, #a78bfa, #6366f1)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              flexShrink: 0,
            }}
          >
            <BookOpen size={20} color="#fff" />
          </div>
          <div>
            <h3 style={{ margin: 0, fontSize: '1.05rem' }}>Mobile Agent Simulation — Walkthrough</h3>
            <p className="text-secondary" style={{ margin: 0, fontSize: '0.82rem' }}>
              Step-by-step guide to testing the phishing QR detection flow.
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
          {/* Download Button */}
          <button
            onClick={handleDownload}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              padding: '0.55rem 1.2rem',
              borderRadius: '8px',
              border: 'none',
              background: 'linear-gradient(135deg, #a78bfa, #6366f1)',
              color: '#fff',
              fontWeight: '600',
              fontSize: '0.875rem',
              cursor: 'pointer',
              transition: 'opacity 0.2s, transform 0.15s',
              boxShadow: '0 4px 14px rgba(99,102,241,0.35)',
            }}
            onMouseEnter={e => { e.currentTarget.style.opacity = '0.88'; e.currentTarget.style.transform = 'translateY(-1px)'; }}
            onMouseLeave={e => { e.currentTarget.style.opacity = '1'; e.currentTarget.style.transform = 'translateY(0)'; }}
            title="Download Walkthrough as .txt"
          >
            <FileDown size={16} />
            Download Walkthrough
          </button>

          {/* Expand/Collapse Button */}
          <button
            onClick={() => setOpen(o => !o)}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '0.4rem',
              padding: '0.55rem 1rem',
              borderRadius: '8px',
              border: '1px solid rgba(167,139,250,0.3)',
              background: 'transparent',
              color: '#a78bfa',
              fontWeight: '600',
              fontSize: '0.875rem',
              cursor: 'pointer',
              transition: 'background 0.2s',
            }}
            onMouseEnter={e => (e.currentTarget.style.background = 'rgba(167,139,250,0.1)')}
            onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
          >
            {open ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
            {open ? 'Hide Steps' : 'View Steps'}
          </button>
        </div>
      </div>

      {/* Expandable Step-by-Step Guide */}
      {open && (
        <div
          style={{
            marginTop: '1.75rem',
            display: 'flex',
            flexDirection: 'column',
            gap: '0.85rem',
            animation: 'fadeIn 0.3s ease',
          }}
        >
          <p style={{ margin: '0 0 0.5rem 0', fontSize: '0.82rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.07em', fontWeight: 600 }}>
            How to Test
          </p>
          {steps.map((step, i) => (
            <div
              key={i}
              style={{
                display: 'flex',
                alignItems: 'flex-start',
                gap: '1rem',
                padding: '0.85rem 1rem',
                borderRadius: '10px',
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid rgba(255,255,255,0.06)',
              }}
            >
              <div
                style={{
                  width: '34px',
                  height: '34px',
                  borderRadius: '8px',
                  background: `${step.color}22`,
                  border: `1px solid ${step.color}44`,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: step.color,
                  flexShrink: 0,
                }}
              >
                {step.icon}
              </div>
              <div>
                <div style={{ fontSize: '0.72rem', fontWeight: 700, color: step.color, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '2px' }}>
                  {step.label}
                </div>
                <div style={{ fontWeight: 600, fontSize: '0.9rem', marginBottom: '3px' }}>{step.title}</div>
                <div className="text-secondary" style={{ fontSize: '0.84rem' }}>{step.desc}</div>
              </div>
            </div>
          ))}

          {/* Technical Stack */}
          <div
            style={{
              marginTop: '0.5rem',
              padding: '0.85rem 1rem',
              borderRadius: '10px',
              background: 'rgba(255,255,255,0.02)',
              border: '1px solid rgba(255,255,255,0.06)',
              display: 'flex',
              gap: '2rem',
              flexWrap: 'wrap',
            }}
          >
            <div>
              <span style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Frontend</span>
              <p style={{ margin: '4px 0 0 0', fontSize: '0.86rem', fontWeight: 500 }}>React + Lucide Icons + CSS Animations</p>
            </div>
            <div>
              <span style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Backend</span>
              <p style={{ margin: '4px 0 0 0', fontSize: '0.86rem', fontWeight: 500 }}>/qr/analyze · /transaction/detect (socRoutes.js)</p>
            </div>
            <div>
              <span style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>State</span>
              <p style={{ margin: '4px 0 0 0', fontSize: '0.86rem', fontWeight: 500 }}>Real-time device health ↔ risk scoring loop</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default WalkthroughPanel;
